### ISSUE TITLE
test.each

### ISSUE THREAD

**Issue by coursar** [lerucom/js-homework4#3]
https://github.com/lerucom/js-homework4/blob/809fc6c1d5d635b4edf50457500b0f5920790452/src/test/lib.test.js#L3-L8

Мы это ещё не проходили, но для таких тестов есть `test.each`:
```javascript
test.each([
  ['Capricorn', 1, 1, 'Козерог'],
  ['...', 1, 29, 'Водолей'],
])('should ... %s', (name, day, month, expected) => {
  const actual = ...;
  expect(actual).toBe(expected);
});
```
И для названий - фактически, вы рассматриваете для каждого знака два сценария:
1. от 22-23 числа месяца до конца месяца
2. от 1 числа до 22-23 числа месяца

Это и нужно было отразить в названии.

**Comment by lerucom** [comment]
@coursar 
Ильназ, ознакомился с https://jestjs.io/docs/en/api#testeachtable-name-fn-timeout , сделал по аналогии:
``` 
test.each([[1, 1, 'Козерог'], [25, 12, 'Козерог'], [25, 1, 'Водолей']])(
    'should actual day %i, month %i, zodiac is %s',
    (day, month, expected) => {
        const actual = calculateZodiacSign(day, month);
        expect(actual).toBe(expected);
    }
);
```
тесты не проходят, в консоли:

```
"C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" test --scripts-prepend-node-path=auto

> js-language@1.0.0 test C:\Users\User\Desktop\js-homework4
> jest

 FAIL  src/test/lib.test.js (6.178s)
  × should actual day 1, month 1, zodiac is Козерог (78ms)
  × should actual day 25, month 12, zodiac is Козерог (6ms)
  × should actual day 25, month 1, zodiac is Водолей (4ms)

  ● should actual day 1, month 1, zodiac is Козерог

    expect(received).toBe(expected) // Object.is equality

    Expected: "Козерог"
    Received: ""

       5 |     (day, month, expected) => {
       6 |         const actual = calculateZodiacSign(day, month);
    >  7 |         expect(actual).toBe(expected);
         |                        ^
       8 |     }
       9 | );
      10 | 

      at toBe (src/test/lib.test.js:7:24)

  ● should actual day 25, month 12, zodiac is Козерог

    expect(received).toBe(expected) // Object.is equality

    Expected: "Козерог"
    Received: ""

       5 |     (day, month, expected) => {
       6 |         const actual = calculateZodiacSign(day, month);
    >  7 |         expect(actual).toBe(expected);
         |                        ^
       8 |     }
       9 | );
      10 | 

      at toBe (src/test/lib.test.js:7:24)

  ● should actual day 25, month 1, zodiac is Водолей

    expect(received).toBe(expected) // Object.is equality

    Expected: "Водолей"
    Received: ""

       5 |     (day, month, expected) => {
       6 |         const actual = calculateZodiacSign(day, month);
    >  7 |         expect(actual).toBe(expected);
         |                        ^
       8 |     }
       9 | );
      10 | 

      at toBe (src/test/lib.test.js:7:24)

Test Suites: 1 failed, 1 total
Tests:       3 failed, 3 total
Snapshots:   0 total
Time:        9.784s
Ran all test suites.
npm ERR! Test failed.  See above for more details.

Process finished with exit code 1

```

**Comment by coursar** [comment]
Всё верно, т.к. switch проверяет на ===, а у вас в функции рассчёта для месяца строка вместо числа.

**Comment by lerucom** [comment]
@coursar 
действительно :) исправил, test.each работает! 27d84e7c30cd3faa2f30c2743b0f97ce01e65351
